# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_of_sniffer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QApplication, QMainWindow, QTextEdit
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
class TextEditLogger(QTextEdit):
    def __init__(self, parent=None):
        super().__init__(parent)

    def write(self, text):
        self.append(text)

    def flush(self):
        pass  # Необходимо для совместимости с sys.stdout
class Form1(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(873, 740)
        self.Label_Analizator_Packets = QtWidgets.QLabel(Dialog)
        self.Label_Analizator_Packets.setGeometry(QtCore.QRect(90, 10, 1081, 71))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(28)
        self.Label_Analizator_Packets.setFont(font)
        self.Label_Analizator_Packets.setObjectName("Label_Analizator_Packets")

        # Изменим отображение в текст эдит таким образом, чтобы перехваченные пакеты отображались там
        self.text_zone = TextEditLogger(self)
        self.text_zone.setGeometry(QtCore.QRect(40, 300, 800, 371))
        self.text_zone.setObjectName("text_zone")

        # Последняя команда как раз перенаправляет отображаемую информацию

        self.pushBatton_finish_work = QtWidgets.QPushButton(Dialog)
        self.pushBatton_finish_work.setGeometry(QtCore.QRect(470, 680, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small")
        font.setPointSize(14)
        self.pushBatton_finish_work.setFont(font)
        self.pushBatton_finish_work.setObjectName("pushBatton_finish_work")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 150, 801, 109))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_network_capture = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_network_capture.setObjectName("lineEdit_network_capture")
        self.gridLayout.addWidget(self.lineEdit_network_capture, 3, 1, 1, 1)
        self.spinBox_time_of_capture = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_time_of_capture.setMaximum(1000)
        self.spinBox_time_of_capture.setProperty("value", 4)
        self.spinBox_time_of_capture.setObjectName("spinBox_time_of_capture")
        self.gridLayout.addWidget(self.spinBox_time_of_capture, 0, 1, 1, 1)
        self.label_interface_of_capture = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(14)
        self.label_interface_of_capture.setFont(font)
        self.label_interface_of_capture.setObjectName("label_interface_of_capture")
        self.gridLayout.addWidget(self.label_interface_of_capture, 1, 0, 1, 1)
        self.label_name_network_capture = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(14)
        self.label_name_network_capture.setFont(font)
        self.label_name_network_capture.setObjectName("label_name_network_capture")
        self.gridLayout.addWidget(self.label_name_network_capture, 2, 0, 2, 1)
        self.lineEdit_interface_capture = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_interface_capture.setObjectName("lineEdit_interface_capture")
        self.gridLayout.addWidget(self.lineEdit_interface_capture, 1, 1, 2, 1)
        self.label_name_time_of_capture = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(14)
        self.label_name_time_of_capture.setFont(font)
        self.label_name_time_of_capture.setObjectName("label_name_time_of_capture")
        self.gridLayout.addWidget(self.label_name_time_of_capture, 0, 0, 1, 1)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(14)
        self.label_obj_information_about_capture = QtWidgets.QLabel(Dialog)
        self.label_obj_information_about_capture.setGeometry(QtCore.QRect(330, 265, 811, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(16)
        self.label_obj_information_about_capture.setFont(font)
        self.label_obj_information_about_capture.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_obj_information_about_capture.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_obj_information_about_capture.setObjectName("label_obj_information_about_capture")
        self.pushButton_save_in_file = QtWidgets.QPushButton(Dialog)
        self.pushButton_save_in_file.setGeometry(QtCore.QRect(40, 680, 371, 41))
        self.pushButton_save_in_file.setObjectName("pushButton_save_in_file")
        self.Label_Analizator_Packets_2 = QtWidgets.QLabel(Dialog)
        self.Label_Analizator_Packets_2.setGeometry(QtCore.QRect(50, 80, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(28)
        self.Label_Analizator_Packets_2.setFont(font)
        self.Label_Analizator_Packets_2.setObjectName("Label_Analizator_Packets_2")
        self.pushBatton_start_capture = QtWidgets.QPushButton(Dialog)
        self.pushBatton_start_capture.setGeometry(QtCore.QRect(40, 262, 211, 35))

        self.pushBatton_stop_sniffing = QtWidgets.QPushButton(Dialog)
        self.pushBatton_stop_sniffing.setGeometry(QtCore.QRect(630, 262, 211, 35))

        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small")
        font.setPointSize(14)
        self.pushBatton_start_capture.setFont(font)
        self.pushBatton_start_capture.setObjectName("pushBatton_start_capture")

        self.pushBatton_stop_sniffing.setFont(font)
        self.pushBatton_stop_sniffing.setObjectName("pushBatton_stop_sniffing")

        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 340, 381, 321))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(10)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Label_Analizator_Packets.setText(_translate("Dialog", "Программа анализа перехваченных пакетов"))
        self.pushBatton_finish_work.setText(_translate("Dialog", "Закрыть программу"))
        self.lineEdit_network_capture.setText(_translate("Dialog", "192.168.1.0"))
        self.label_interface_of_capture.setText(_translate("Dialog", "Интерфейс по которому производить захват"))
        self.label_name_network_capture.setText(_translate("Dialog", "Сеть захвата"))
        self.label_name_time_of_capture.setText(_translate("Dialog", "Период времени захвата пакетов"))
        self.label_obj_information_about_capture.setText(_translate("Dialog", "Перехваченные пакеты"))
        self.pushButton_save_in_file.setText(_translate("Dialog", " Сохранить в файл"))
        self.Label_Analizator_Packets_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt;\">Входные данные</span></p></body></html>"))
        self.pushBatton_start_capture.setText(_translate("Dialog", "Начать захват"))
        self.pushBatton_stop_sniffing.setText(_translate("Dialog", "Прекратить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    first_part = QtWidgets.QDialog()
    ui = Form1()
    ui.setupUi(first_part)
    first_part.show()
    sys.exit(app.exec_())
